spring:
  application:
    name: talk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/blow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 9001


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

