spring:
  application:
    name: talk-service
  datasource:
    url: jdbc:postgresql://localhost:5432/blow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver



