spring:
  application:
    name: gate-way
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTION

      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1

        - id: talk-service
          uri: lb://talk-service
          predicates:
            - Path=/talk/**
          filters:
            - StripPrefix= 1



server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true





