spring:
  application:
    name: gate-way
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:

      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**



server:
  port: 8080


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true





